Remove stepper for adults_nth
teamforus/forus-frontend pull request #259
Opened 2024-08-12 12:29 UTC by RobinMeles

## Changes description & testing suggestions

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

2024-08-13 13:47 UTC, dev-rminds approved these changes, later dismissed

2024-08-13 13:49 UTC, lexlog commented
@RobinMeles are there any dependencies for the merge/release of this change?

2024-08-13 14:02 UTC, lexlog requested changes
has dependencies https://github.com/teamforus/forus-frontend-react/pull/259#issuecomment-2286334534
assigned on @RobinMeles until further notice

2024-09-03 11:35 UTC, lexlog approved these changes, later dismissed

2024-09-04 09:01 UTC, merged