Update styles for bulk and csv upload forms
teamforus/forus-frontend pull request #270
Opened 2024-08-21 13:35 UTC by ateamcms

## Changes description & testing suggestions

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

2024-08-28 16:01 UTC, lexlog commented
QA:
- [x] tested download/upload on vouchers, transactions, prevalidations

Feedback:
- prevalidations fund dropdown has issues with responsivity if length of fund name is short
<img width="224" alt="Screenshot 2024-08-28 at 17 58 47" src="https://github.com/user-attachments/assets/581316ed-9d49-4fe3-be52-f0983eef419f">

we can reuse solution from vouchers page to have fixed size of dropdown
<img width="315" alt="Screenshot 2024-08-28 at 17 59 20" src="https://github.com/user-attachments/assets/7e95a3ae-81f7-40a7-a901-fadc8e30949d">

- also would be good to add same spacing between end of name and arrow, as it is added in figma and vouchers dropdown

2024-09-02 12:47 UTC, irinaBerendeeva87 requested changes
### Checked:
**Aanvragers toevoegen**
**Dropdown**:
❌  selected fund is displayed after refreshing the pages
❌ displayed selected fund after opening the dropdown

**Buttons**
✅ Cancel
✅ Upload
✅ Close 

**Text**
✅ Errors

✅ Uploading 

----------------------

**Sponsor transactions**

Size:
❌ Based on design  the size of the file modal should be the same as a buttons 
<img width="573" alt="Screenshot 2024-09-02 at 14 23 44" src="https://github.com/user-attachments/assets/73fd439d-d1b9-47e1-9a05-4eaf4bc84e54">

✅  Uploading

**Buttons**
✅ Cancel
✅ Upload
✅ Close 

**Text**
✅ Errors
 
 ------------------------
 
 **Vouchers uploader**
 ✅ Dropdowns
 ❌  Uploading is not possible to close  downloads modal help only reload, when reproducing https://github.com/teamforus/DevOps/issues/940

 **Buttons**
✅ Annuleren
✅ Upload

✅ Error text

-------------------------
**Out of the scope( not related to this PR):**
 while switching from Meedoenpakket  to Meedoenregeling or Kindpakket the сolumns in the table are inverted and then displayed table related to the fund

https://github.com/user-attachments/assets/d5a54a45-5a1f-4822-95a6-d095059d116d

2024-09-03 12:54 UTC, irinaBerendeeva87 approved these changes
Checked:
" Uploading is not possible to close downloads modal help only reload, when reproducing https://github.com/teamforus/DevOps/issues/940 " this fixed an error check added. If there is an error during loading, then an error message appears
 
<img width="319" alt="Screenshot 2024-09-03 at 14 47 47" src="https://github.com/user-attachments/assets/b72608b1-c16b-42b9-a83e-920de76e99ee">

2024-09-03 18:28 UTC, lexlog approved these changes

2024-09-03 18:28 UTC, merged