Epic.profiles
teamforus/forus-frontend pull request #493
Opened 2024-12-06 08:19 UTC by dev-rminds

## Changes description & testing suggestions

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

2024-12-10 11:29 UTC, irinaBerendeeva87 requested changes
### Checked:
#### Persons page:
**Filters:**
✅ page has a description per column
✅ page has sideways scrolling.

❌ Sponsor can filter data by fund:
 Sponsor can see a message  when there is no data for a specific fund
currently wrong text of the message 
<img width="955" alt="Screenshot 2024-12-09 at 13 58 16" src="https://github.com/user-attachments/assets/92fc52c7-69ee-4985-9592-a5ddf19673cc">

❌ Sponsor can filter data by: **will be fixed separately**
- Date of birth from
- Date of birth Date of birth till
- Last login from
- Last login till
- Postalcode single select
- Number of vouchers range
- Woonplaats single select
<img width="846" alt="Screenshot 2024-12-10 at 11 44 10" src="https://github.com/user-attachments/assets/6267060a-6cc7-4400-95dc-51a4c5691af8">

**Search:**
✅ by new first/ last name
✅ by old  first/ last name
✅ by email
✅ by bsn


#### Roles:
**View-only role without others' permissions:**
✅ sponsor can see  Page Persons on a side menu
✅ sponsor can see the list of personal data
✅ sponsor can see data of person :
- Personal data
- Account details
- Contact details
- Bank accounts

✅ sponsor cannot edit data
✅ sponsor can see history changes
- in Personal data
- in Contact details

**View-only role with "Voucher beheerder" role:**
✅ sponsor can see  Page Persons on a side menu
✅ sponsor can see the list of person data
✅ sponsor can see data of person :
- Personal data
- Account details
- Contact details
- Bank accounts
- Vouchers
- Declarations

✅ sponsor cannot edit data
✅ sponsor can see history changes
- in Personal data
- Contact details
-------------------
### "Persoonsdossiers beheerder" role:
**editing:**
- First name
- Last name 
- Date of birth

❌ sponsor cannot add future date
<img width="302" alt="Screenshot 2024-12-09 at 16 01 46" src="https://github.com/user-attachments/assets/cbf981bc-672a-4a2a-a8ba-ea7d3f3e5f08">

info block
❌ each field has its own text
<img width="607" alt="Screenshot 2024-12-09 at 16 07 01" src="https://github.com/user-attachments/assets/719b9310-b41d-4c04-9229-56367832c84c">
 
❌  edit modal has Dutch translation
<img width="671" alt="Screenshot 2024-12-09 at 16 07 16" src="https://github.com/user-attachments/assets/f116ee28-86f2-4530-9f7d-2c45b06a6a47">

❌ buttons in Dutch translation
<img width="562" alt="Screenshot 2024-12-09 at 16 12 53" src="https://github.com/user-attachments/assets/0f8ea2bc-457a-4479-8051-0ba485eb2936">

**Contact details block**
❌  sponsor can see all confirmed emails in the block 
if the requester  added 2 additional emails  but the sponsor can see only main email address :
<img width="1096" alt="Screenshot 2024-12-09 at 16 23 11" src="https://github.com/user-attachments/assets/fc3e6edd-027d-45f9-b49a-f73272f25d54">

<img width="503" alt="Screenshot 2024-12-09 at 16 35 46" src="https://github.com/user-attachments/assets/169348ac-85b4-4eff-9c7f-a2668d0c9a91">

<img width="848" alt="Screenshot 2024-12-09 at 16 36 03" src="https://github.com/user-attachments/assets/9e9b355f-30a4-4b07-ac83-8d9991b04a76">

❌ text  in infobox
<img width="575" alt="Screenshot 2024-12-10 at 09 44 29" src="https://github.com/user-attachments/assets/7331b7a2-fcdc-482b-a443-86571bdadf31">

**Bank accounts block**
✅ Counter changed after  adding new Bank account data
✅ added manually can edited
✅ added manually can delete


**Vouchers block**
✅ Counter changed after  create new voucher 
✅ transitions(  Bekijken lead to  specific voucher
❌ tbl contains vouchers with different statuses
tbl has vouchers with only active status 

https://github.com/user-attachments/assets/09466e54-7985-42e2-8ebe-1ee866c09864

**Payouts block**
❌ tbl contains Payouts with different statuses
tbl has no Payouts  even if sponsor created Payout  but not paid it out and then paid out. 

https://github.com/user-attachments/assets/b5d9cf26-d7a8-46ac-b012-bdd70b950a6b

**Declarations block**
✅ Counter changed after  create new declaration 
✅  tbl contains declarations with different statuses
✅ transitions(  Bekijken lead to  specific declaration )

### WEBSHOP
✅ new page Gegevens in Mijn tegoeden menu
✅ requester can edit their personal data 

❌ infobox with an explanation where a requester can change email
there is no infobox. 
<img width="553" alt="Screenshot 2024-12-09 at 16 39 55" src="https://github.com/user-attachments/assets/44b2a0c6-d835-4eb6-ac6a-7277fdda16c7">

❌ Popups in Dutch 
<img width="334" alt="Screenshot 2024-12-10 at 10 16 43" src="https://github.com/user-attachments/assets/f78319b4-f49d-4ea1-8b36-8c3dc6a4f7f2">

✅ each bank account data in a separate block
✅ error 422 and 429
✅ checked in different implementations

2024-12-10 16:00 UTC, irinaBerendeeva87 reviewed
### Checked:

Fixed:
✅ Sponsor can filter data by fund
✅ Sponsor cannot add future date
✅ Sponsor can see all confirmed emails in the block
✅ tbl contains vouchers with different statuses
✅ infobox with an explanation where a requester can change email

2024-12-11 12:07 UTC, lexlog approved these changes, later dismissed

2024-12-12 08:59 UTC, irinaBerendeeva87 approved these changes
### Checked:

✅ translations

2024-12-12 09:22 UTC, merged