Epic: deepl integration
teamforus/forus-frontend pull request #526
Opened 2024-12-24 04:29 UTC by dev-rminds

## Changes description & testing suggestions

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

2024-12-24 04:40 UTC, dev-rminds commented
**Testing Scope:**

- Most inline texts have been moved to translation files. However, a few instances remain untranslated, which can be addressed in a follow-up task/pull-request.  
- The primary focus of testing is regression testing, ideally having 2 instances open and going from page to page to make sure the texts are the same for main language and there are no visual issues or missing texts / visible translation keys.  

After Milestone 2, we can make a list of texts that are not yet translated for further translation.

2025-01-03 12:11 UTC, irinaBerendeeva87 commented
@dev-rminds  Please describe how to set up translations and environment step by step.

2025-01-03 13:51 UTC, irinaBerendeeva87 requested changes
### Checked:
**Webshop**
✅ dropdown translator(web vers)
❌ dropdown translator(mobile vers)
not visible dropdown elements

<img width="657" alt="Screenshot 2025-01-03 at 11 18 17" src="https://github.com/user-attachments/assets/6461fc6a-42cb-47b5-a8ba-cbfb669d85a6" />

https://github.com/user-attachments/assets/fad997a1-bfd2-4fd4-8ef7-5c5a96f307cb

✅ hover in dropdown
✅ choose any language  translate the page content
✅ Navbar
✅ Log in buttons
❌ Main menu items:
for some org  did not translate

<img width="1151" alt="Screenshot 2025-01-03 at 11 48 54" src="https://github.com/user-attachments/assets/f9918afb-b4e5-4b64-bcc3-4c556d212e09" />

✅ Search bar (text)
**When logged in:**
✅ Uitloggen
✅Menu items right sidebare when logged in
✅ My vouchers button
❌ missing visible translation key in filter:
 - on Reservations page 

<img width="329" alt="Screenshot 2025-01-03 at 11 58 07" src="https://github.com/user-attachments/assets/73659833-eb3c-4b98-92af-b5706c541eb3" />

- /aanbod
<img width="327" alt="Screenshot 2025-01-03 at 14 45 49" src="https://github.com/user-attachments/assets/c8fc7f25-cc51-4b25-bb3e-78f99f5d7fc5" />


✅Footer standard links bottom
✅ How it works link (header text homepage)
✅ no errors in the console
✅ checked in different implementations

2025-01-09 11:57 UTC, irinaBerendeeva87 approved these changes
### Checked:
 Fixed:
-  not visible dropdown elements
-  translation key in filter:
✅ bookmark 
❌ values ​​in dropdown on aanbod in dropdown Distance
<img width="265" alt="Screenshot 2025-01-09 at 12 18 22" src="https://github.com/user-attachments/assets/a6d525c6-170a-45ca-8cd0-c406d2cbe5cf" />

 
✅ no errors in the console
✅ error 422 and 429
✅ checked in different implementations
 
 **will fix after merge:**
 - lang dropdown moved to the left side (only vergoedingen )
 
<img width="676" alt="Screenshot 2025-01-09 at 11 22 57" src="https://github.com/user-attachments/assets/088ff51f-04c0-4e55-a6c2-a3cbeadc23a8" />

- focus in mobele vers

https://github.com/user-attachments/assets/4745defb-33f9-4c5b-bf2b-06f76bf33e55

2025-01-09 12:20 UTC, merged